# Generated by Django 4.0.3 on 2022-03-10 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('demo_time', models.DateField()),
                ('created_at', models.DateField()),
                ('link_repo', models.CharField(max_length=255)),
            ],
        ),
    ]
